language: minimal

dist: bionic

addons:
   apt:
      packages: debootstrap

script:
   - wget http://deb.debian.org/debian/pool/main/l/live-build/live-build_20190311_all.deb && sudo dpkg -i live-build_20190311_all.deb
   - cd buster
   - sudo lb clean --purge
   - lb config
   - travis_wait 30 sudo lb build
   - sha512sum sharpbang-buster-*.hybrid.iso > sha512sum.amd64

deploy:
   provider: releases
   api_key: "$GITHUB_TOKEN"
   file: 
      - "sharpbang-buster-10.3.8-amd64.hybrid.iso"
      - "sha512sum.amd64"
   skip_cleanup: true
   on:
      tags: true

