language: minimal

services: docker

before_install:
  - docker pull debian
  - docker run debian /bin/sh -c "apt update && apt install -y live-build"
  - docker run debian /bin/sh -c "mkdir /iso"
  - docker cp buster debian:/iso/
  - docker run debian /bin/sh -c "cd /iso/buster && lb build"
  - docker cp debian:/iso/buster/sharpbang-buster-10.10.0-amd64.hybrid.iso /iso/debian:/buster/sha512sum.amd64 /

script: lb build

deploy:
   provider: releases
   api_key: "$GITHUB_TOKEN"
   file: 
      - "/sharpbang-buster-10.10.0-amd64.hybrid.iso"
      - "/sha512sum.amd64"
   skip_cleanup: true
   on:
      tags: true

