language: minimal

dist: bionic

addons:
   apt:
      packages:
         - debootstrap

script:
   - wget http://deb.debian.org/debian/pool/main/l/live-build/live-build_20190311_all.deb && sudo dpkg -i live-build_20190311_all.deb
   - cd buster
   - sudo lb clean --purge
   - lb config
   - sudo lb build

deploy:
   provider: releases
   api_key: "869ef64f49c4009b3a9baf13aae36cddb023de8e"
   file: "sharpbang-buster-amd64.hybrid.iso"
   skip_cleanup: true
   on:
      tags: true

