#!/bin/sh

# SET --mirror-bootstrap TO YOUR FASTEST LOCAL MIRROR
# It will reduce build time, but will not be used in the produced iso.

# Set --image-name to the build version, *without* the architecture,
# which will be appended automatically.

lb config noauto \
   --apt-source-archives 'false' \
   --apt-indices 'false' \
   --archive-areas 'main contrib non-free' \
   --bootappend-live 'boot=live components locales=en_GB.UTF-8 keyboard-layouts=gb timezone=Europe/London' \
   --clean \
   --debian-installer 'live' \
   --debian-installer-distribution 'daily' \
   --distribution 'sid' \
   --firmware-binary 'true' \
   --firmware-chroot 'true' \
   --image-name 'sharpbang-sid-20200403' \
   --iso-application 'SharpBang' \
   --iso-publisher 'SharpBang GNU/Linux' \
   --iso-volume 'SHARPBANG_SID' \
   --mirror-binary 'https://deb.debian.org/debian' \
   --mirror-bootstrap 'https://deb.debian.org/debian' \
   --quiet \
   --system 'live' \
   "${@}"
