#!/bin/sh

# SET --mirror-bootstrap TO YOUR FASTEST LOCAL MIRROR
# It will reduce build time, but will not be used in the produced iso.

# Set --image-name to the build version, *without* the architecture,
# which will be appended automatically.

lb config noauto \
   --image-name 'sharpestbang' \
   --mirror-bootstrap https://cdn-aws.deb.debian.org/debian/ \
   --mirror-binary https://deb.debian.org/debian \
   --debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
   --bootappend-live "boot=live components locales=en_GB.UTF-8 keyboard-layouts=gb timezone=Europe/London" \
   --apt-options "-y" \
   --apt-recommends false \
   --apt-source-archives false \
   --apt-indices false \
   --distribution sid \
   --archive-areas "main contrib non-free" \
   --clean \
   --debian-installer live \
   --debian-installer-gui true \
   --debian-installer-distribution sid \
   --firmware-binary true \
   --firmware-chroot true \
   --iso-application SharpestBang \
   --iso-publisher 'SharpestBang GNU/Linux' \
   --iso-volume 'SHARPESTBANG' \
   --memtest memtest86+ \
   "${@}"
