#!/bin/sh

set -e

echo "Starting build at $( date )" | tee build.log

# config/lb_patches is a script to make temporary changes to live-build.
# Please keep these to a minimum!
applied_patches=false
if [ -x config/lb_patches.sh ]
then
    echo "Applying live-build patches..." | tee -a build.log
    config/lb_patches.sh apply 2>&1 | tee -a build.log
    applied_patches=true
fi

lb build noauto "${@}" 2>&1 | tee -a build.log

if [ "$applied_patches" = 'true' ]
then
    if [ -x config/lb_patches.sh ]
    then
        echo "Removing live-build patches..." | tee -a build.log
        config/lb_patches.sh remove 2>&1 | tee -a build.log
    else
        echo "Failed to execute 'lb_patches remove'" | tee -a build.log
        exit 1
    fi
fi
